$(document).ready(function()
{
    $("input.f1").mouseenter(function()
    {
    $("input.f1").css("background","#FF0087");
    $("input.f1").css("color","#FFF");
    })
    $("input.f1").mouseleave(function()
    {
    $("input.f1").css("background","#00FF78");
    $("input.f1").css("color","#000");
    })
     $("input.f2").mouseenter(function()
    {
    $("input.f2").css("background","#FF0087");
    $("input.f2").css("color","#FFF");
    })
    $("input.f2").mouseleave(function()
    {
    $("input.f2").css("background","#00FF78");
    $("input.f2").css("color","#000");
    })
     $("input.f3").mouseenter(function()
    {
    $("input.f3").css("background","#FF0087");
    $("input.f3").css("color","#FFF");
    })
    $("input.f3").mouseleave(function()
    {
    $("input.f3").css("background","#00FF78");
    $("input.f3").css("color","#000");
    })
     $("input.in2").mouseenter(function()
    {
    $("input.in2").css("background","#FF0087");
    $("input.in2").css("color","#FFF");
    })
    $("input.in2").mouseleave(function()
    {
    $("input.in2").css("background","#00FF78");
    $("input.in2").css("color","#000");
    })
     $("input.f5").mouseenter(function()
    {
    $("input.f5").css("background","#FF0087");
    $("input.f5").css("color","#FFF");
    })
    $("input.f5").mouseleave(function()
    {
    $("input.f5").css("background","#00FF78");
    $("input.f5").css("color","#000");
    })
     $("input.f4").mouseenter(function()
    {
    $("input.f4").css("background","#FF0087");
    $("input.f4").css("color","#FFF");
    })
    $("input.f4").mouseleave(function()
    {
    $("input.f4").css("background","#00FF78");
    $("input.f4").css("color","#000");
    })
    $("input.fi").mouseenter(function()
    {
    $("input.fi").css("background","#FF0087");
    $("input.fi").css("color","#FFF");
    })
    $("input.fi").mouseleave(function()
    {
    $("input.fi").css("background","#00FF78");
    $("input.fi").css("color","#000");
    })
})