$(document).ready(function()
{
    $("input.in1").mouseenter(function()
    {
    $("input.in1").css("background","#FF0087");
    $("input.in1").css("color","#FFF");
    })
    $("input.in1").mouseleave(function()
    {
    $("input.in1").css("background","#00FF78");
    $("input.in1").css("color","#000");
    })
     $("input.in2").mouseenter(function()
    {
    $("input.in2").css("background","#FF0087");
    $("input.in2").css("color","#FFF");
    })
    $("input.in2").mouseleave(function()
    {
    $("input.in2").css("background","#00FF78");
    $("input.in2").css("color","#000");
    })
})